/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function startApp(bindAddress: string, jsCallback: (...args: any[]) => any): object
export function stopApp(): void
export function addController(controllerName: string, controllerClass: (...args: any[]) => any): void
export function registerRoute(pattern: string, handler: JsUnknown): void
